apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsers-deployment
  namespace: devopsers
  labels:
    app: devopsers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsers
  template:
    metadata:
      labels:
        app: devopsers
    spec:
      containers:
        - name: devopsers-app
          image: ahmedsabeh/devopsers:1.23
          imagePullPolicy: Always
          ports:
            - containerPort: 80
